<?php
namespace Aura\Framework\Web;
use Aura\Signal\Manager as SignalManager;
use Aura\Signal\HandlerFactory;
use Aura\Signal\ResultFactory;
use Aura\Signal\ResultCollection;
use Aura\Web\Context;
use Aura\Web\ResponseTransfer;

/**
 * Test class for Page.
 * Generated by PHPUnit on 2011-05-27 at 11:01:03.
 */
abstract class AbstractPageTest extends \PHPUnit_Framework_TestCase
{
    protected $page_name;

    protected function newPage($params = array())
    {
        $class = "\Aura\Framework\Web\\{$this->page_name}\Page";
        return new $class(
            new Context($GLOBALS),
            new SignalManager(new HandlerFactory, new ResultFactory, new ResultCollection),
            new ResponseTransfer,
            $params
        );
    }
}