<?php
namespace Aura\Framework;

namespace View\Helper;

/**
 * Test class for AssetHref.
 * Generated by PHPUnit on 2011-10-06 at 15:19:08.
 */
class AssetHrefTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var AssetHref
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        parent::setUp();
        $this->object = new AssetHref;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        parent::tearDown();
    }

    /**
     * @todo Implement testSetBase().
     */
    public function testSetBase()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement test__invoke().
     */
    public function test__invoke()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
